// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoBj3xauvV80G-YcOzNPXRTx-1teoCZvE',
    appId: '1:1077351022774:web:32c59ee2a7489f7ce22617',
    messagingSenderId: '1077351022774',
    projectId: 'e-business-138ec',
    authDomain: 'e-business-138ec.firebaseapp.com',
    storageBucket: 'e-business-138ec.appspot.com',
    measurementId: 'G-F8S3TMVH91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn5e-PsJPAfF_IQCK-ua3FWTdwzIHgruA',
    appId: '1:1077351022774:android:b96da0f5548cb3a3e22617',
    messagingSenderId: '1077351022774',
    projectId: 'e-business-138ec',
    storageBucket: 'e-business-138ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACFwu4BB9AbKEEGDiLKmwFh_Uzpbjvu54',
    appId: '1:1077351022774:ios:7ac0b253c03848d4e22617',
    messagingSenderId: '1077351022774',
    projectId: 'e-business-138ec',
    storageBucket: 'e-business-138ec.appspot.com',
    iosClientId: '1077351022774-ujk95b3tfihumejrdptcj7oq5atufekv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebusiness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACFwu4BB9AbKEEGDiLKmwFh_Uzpbjvu54',
    appId: '1:1077351022774:ios:7ac0b253c03848d4e22617',
    messagingSenderId: '1077351022774',
    projectId: 'e-business-138ec',
    storageBucket: 'e-business-138ec.appspot.com',
    iosClientId: '1077351022774-ujk95b3tfihumejrdptcj7oq5atufekv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebusiness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoBj3xauvV80G-YcOzNPXRTx-1teoCZvE',
    appId: '1:1077351022774:web:3cfb0998b97df899e22617',
    messagingSenderId: '1077351022774',
    projectId: 'e-business-138ec',
    authDomain: 'e-business-138ec.firebaseapp.com',
    storageBucket: 'e-business-138ec.appspot.com',
    measurementId: 'G-HCDN53XEMQ',
  );
}
